services:
  postgres_service:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  
  user-app_service:
    build:
      network: host
      context: ./
      dockerfile: Dockerfile
    
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres_service:5432/postgres

    ports:
      - 3000:3000
    
    depends_on:
      - postgres_service